### ISSUE TITLE
How to use the Senseglove with the Hololens (1) 

### ISSUE THREAD

**Issue by telion2** [Adjuvo/SenseGlove-Unity#14]
**Context & Goal**

We were trying to set up the Senseglove with the Hololens 1, but we had no luck till now. 
We essentially wanted to test the User Experience and the ability to distinguish Objects in AR. 

**Our Attempts**

So our approch was to setup a senseglove Unity project with vive trackers and remote it to the Hololens using the holographic remoting.
This required steamVR and the vive Input Utility in order to use the vive trackers. 
After some research we were also able to extract their position so we theoretically could send them to the Hololens and transform them. 
Then we tried to setup the Hololens by first importing the MRTK 2.0.0 (Mixed Reality Toolkit) into our project. 
This required us to switch to UWP and we run into this issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5754 

Basically steamVr requires OpenVr and uses the Standalone build setting and MRTK needs the  UWP settings, so that we can run our app remotly on the Hololens. 
In other words: OpenVR and MRTK are incompatible when using Hololens. 

Now since this sdk provides a SenseGlove_ARGlove for AR I was wondering how to setup a project where the user can interact with GameObjects (that are grabbable by the senseglove of course) in AR? 
This question has the following important subquestions:  

1. How should the position of the SenseGlove be retrieved? (Or: Is using Vive Trackers the best option, or are there better and easier alternatives?) 
2. How should the postional data be transformed into Hololens Coordinates?
3. How the information about from the SenseGlove and the Vive Trackers or the processed scene reach the Hololens? (Remoting? Server in between? ...?)

**Technology/Software used**
-Vive Tracker setup
-Hololens 1 
-SenseGlove

-Unity 2018.3.
-SteamVR (with OpenVR) 
-ViveInputUtility-Unity
-MRTK 2.0.0
(Will soon check all the versions of the Software we used. Couldn't remember all the numbers)

**Comment by MaxLammers** [comment]
Hi Telion,

This is more of an architecture question than a Sense Glove SDK issue. We have not personally built applications for the Hololens, but will do our best to help out.

The intended use of the _SenseGlove_ARGlove_ prefab and -script you mention is to provide a way to interact with digital objects without drawing a full hand model (since you already see your own hand in AR). We created it for a project that used a combination of a _Meta2_ and Vive trackers, made fully in Unity. The Prefab is already rigged to allow you to interact with any object that has one of the _SenseGlove_Interactable_ scripts attached, and feel any object that has a _SenseGlove_Material_ attached.

To answer your subquestions:

1) The Sense Gloves do not have built-in positional tracking, but you can make their hand model a child of any Unity GameObject of which you can control the position (using Vive Trackers, IMU suits, WASD, etc). We recommend the use of Vive trackers, as they have a (relatively) small size and do not require additional calibration for SteamVR, but they are not needed for the SDK to work. Some of our clients are using Occulus Touch controllers instead. 

2) That depends entirely on which tracking solution you use. If we assume that Unity applications on the Hololens still use the Unity Coordinate system, there shouldn't be any conversion required from the Sense Glove SDK or Vive Trackers: Both SDK's send their data in Unity coordinates. If you are using any other solution, you might require a conversion to Unity coordinates.

3) If you are not planning to run the application on the Hololens directly, a good option would be to send the processed scene (or rather, the next frame for the headset) to the Hololens. This method saves on processing time on the headset and removes the need for coordinate conversion. How one goes about doing that is quite technical and beyond the scope of the Sense Glove SDK.
