### ISSUE TITLE
Failed to resolve assembly:SGCoreCs

### ISSUE THREAD

**Issue by maoxingzhao** [Adjuvo/SenseGlove-Unity#22]
AssemblyResolutionException: Failed to resolve assembly: 'SGCoreCs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.TypeReference.Resolve () (at <28cdca1704d2491781795499c297b78b>:0)

**Comment by maoxingzhao** [comment]
Is it not compatible with Android?

**Comment by MaxLammers** [comment]
Dear maoxingzhao,

Version 2.0 of our Unity plugin should be compatible with Android via a different version of the SGCoreCs.dll called SGCoreCsAndr.dll. Though different in filename (in order to exist in the same folder), it's configured to be included in every **non-editor** android build. We have successfully built and run Android applications using this exact configuration.

Are you perhaps trying to run your simulation on an android device from the Unity Editor's Build&Run function?

**Comment by MaxLammers** [comment]
After receiving Mao's project via mail, we established there were indeed build errors in this particular project (Unity Editor 2020.3.10, using OpenXR for VR integration). No such issue in our projects using Unity Plugin 2.0 and Unity 2020.4.5f1. Perhaps there's some different build configurations?

We're able to successfully get the project to build using the following steps:
