### ISSUE TITLE
Wrong hand orientation in VR

### ISSUE THREAD

**Issue by olemid** [Adjuvo/SenseGlove-Unity#29]
Hello again,

I have been trying to get senseglove up and running in VR on Quest 2 Link, however even in a new project I can not manage to get the hands to point in the correct orientation. 

I have attached this image of what it looks like from my point of view when I reach my hand out as for a handshake, it points straight towards me. It is also flat when my hand is vertical. The position seems to be correct for me, though the hand seems to move around a pivot instead of around my wrist.
![HandWrong](https://user-images.githubusercontent.com/54032252/208641607-2171dc5c-a26f-4437-8746-9209d6d51f41.jpg)

I'm sure I've made a mistake, but it's not clear to me where, or how I can fix it. I have attached the controller to the glove exactly like required, so it's not that. 

Any guidance is appreciated.

**Comment by olemid** [comment]
Alright, update here. I changed the tracking method from auto to manual, and now it works as expected.
![image](https://user-images.githubusercontent.com/54032252/208646981-85895f02-9f08-4a7f-88ef-bfced44e34c7.png)

I am running Unity 2019.4 and legacy VR, so maybe the auto setup is for XR management.

**Comment by MaxLammers** [comment]
Hi olemid,

The `UnityXR` mode of the `wristTrackingMethod` will grab the `devicePosition` and `deviceRotation` via `UnityEngine.XR.InputDevice` and applies (hard-coded) offsets for the appropriate controller. If the `name` of the HMD contains "Quest" or "Oculus" it should use the proper Quest 2 controller offsets. This is indeed based on Unity's XR plugin management system introduced in Unity 2019. For project that do not (or cannot) use the XR management system there is an alternative approach, which it seems you've already found.

Since you were able to solve your issue, I'll mark this as resolved.
