### ISSUE TITLE
Wrong Offset Meta Quest Pro Controller

### ISSUE THREAD

**Issue by LauraKatarina** [Adjuvo/SenseGlove-Unity#37]
When attaching the Meta Quest Pro Controller to the senseglove, the application does not recognize the hardware type correctly and displays a wrong position and rotation of the hands. As a quick fix we changed wristTrackingOffsets in \Assets\SenseGlove\Scripts\Devices\SG_HapticGlove.cs to SGCore.PosTrackingHardware.QuestProController (Line 64 and 293).

**Comment by MaxLammers** [comment]
This is a known problem with the Oculus XR Plugin: When calling UnityEngine.XR.InputDevice.name, it identifies itself as "quest 2", rather than "quest pro" - leading to us using the wrong offsets. This issue also exists in the Oculus Plugin for Unity.

This workaround will work, but we have an easier solution available: In the `SG_HapticGlove` script, you can set the `wristTrackingMethod` (Default value `UnityXR`) to `UnityXR_ManualOffsets`. This will casue a second dropdown to apprear, which will let you explicitly select the `SGCore.PosTrackingHardware.QuestProController` offsets for your build.

For more info on this, you can check out [our documentation website](docs.senseglove.com/unity/wristTracking.html).
